# Generated by Django 5.2 on 2025-07-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMain',
            fields=[
                ('task_main_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_main_ID', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assign_type', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmain')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('assigned_by', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmain')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmain')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmain')),
            ],
        ),
    ]
